Add additional comments and checks

diff --git a/btrfs-borg b/btrfs-borg
--- a/btrfs-borg
+++ b/btrfs-borg
@@ -128,23 +128,27 @@ EOF
     notfound=1
 fi
 # Check for necessary requirements
-for c in install btrfs borg; do
+for c in cut install btrfs borg stat; do
     type $c >/dev/null 2>&1
     if [ $? -ne 0 ]; then
        echo "$c not found"
        notfound=1
     fi
 done
+if [ `echo -n $BASH_VERSION | cut -d. -f1` -lt 4 ]; then
+    echo "Found bash version $BASH_VERSION."
+    echo "Exiting, because >=4 is needed."
+    exit 1
 if [ -z ${notfound+x} ]; then
     echo -n "Proceed? "
     read choice
     case "$choice" in
         yes | y | Yes | YES )
-            echo "Here be dragons..."
+            echo "Proceeding despite danger."
             break
             ;;
         no | n | No | NO )
-            echo "Exiting"
+            echo "Exiting safely."
             exit 1
             ;;
         * )
@@ -176,6 +180,8 @@ remuser=`echo $repo | cut -d@ -f1`
 remhost=`echo $repo | cut -d@ -f2 | cut -d: -f1`
 remrepo=`echo $repo | cut -d: -f2`
 
+# TODO: non-iterable sanity checks TARGET FOR CLEANUP!
+# Check for existence of intended borg REPO
 if [ -n "$remuser" ] && [ -n "$remhost" ] && [ -n "$remrepo" ]; then
     ssh $remuser@$remhost "test -e $remrepo/config"
 elif [ ! -f $repo/config ]; then
