Cleanups, reorganisation, better comments, plus one new function
check_permissions() is new

diff --git a/btrfs-borg b/btrfs-borg
--- a/btrfs-borg
+++ b/btrfs-borg
@@ -58,77 +58,31 @@ Finally root is required to remove subvolumes, unless
 That said, I firmly maintain that normal user subvolume creation and
 deletion should be avoided for the foreseeable future.
 
-EOF
+Btrfs-borg will terminate now.
 
-    notfound=1
+EOF
+    exit 1
 fi
 # Check for requirements
 for c in cut install btrfs borg stat; do
     type $c >/dev/null 2>&1
     if [ $? -ne 0 ]; then
-        echo "$c not found"
-        notfound=1
+        echo "Required dependency $c not found."
+        echo "Btrfs-borg will terminate now, because $c is needed"
+        exit 1
     fi
 done
 if [ $(echo -n $BASH_VERSION | cut -d. -f1) -lt 4 ]; then
     echo "Found bash version $BASH_VERSION."
-    echo "Exiting, because >=4 is needed."
+    echo "Btrfs-borg will terminate now, because >=4 is needed."
     exit 1
-    if [ -z ${notfound+x} ]; then
-        echo -n "Proceed? (Please type no)"
-        while true; do
-            read choice
-            case "$choice" in
-                yes | y | Yes | YES )
-                    echo "Proceeding despite danger."
-                    break
-                    ;;
-                no | n | No | NO )
-                    echo "Exiting safely."
-                    exit 1
-                    ;;
-                * )
-                    printf "Please answer yes or no\n\n"
-                    ;;
-            esac
-        done
-    fi
 fi
 
 echo "Make this file pull btrfs-borg-functions from the right location at install time"
 echo "Someday uncomment the following line...when the functions are reasonably complete..."
 echo "source /usr/lib/btrfs-borg-functions"
 
-# Checks to make sure the top-down full-tree is visible to btrfs-borg
-# and that only admins can access it.
-create_mount_points
-admin_mod=( $(stat -L -c "%G:%U %a" $ADMIN_DIR) )
-admin_own=${admin_dir_mod[0]}
-other_perm=${admin_dir_mod[1]:2}
-
-if [ $admin_own != "root:$ADMIN_GROUP" -o $admin_own != "root:root" ] && [ $other_perm -ne 0 ]; then
-    echo -n "Unsafe permissions for $ADMIN_DIR.  Fix? (y/n) "
-    while true; do
-        read choice
-        case "$choice" in
-            yes | y | Yes | YES )
-                chown root:root $ADMIN_DIR
-                chmod 750 $ADMIN_DIR
-                cat <<EOF
-
-Owner/permissions changed to root:root/750.  To allow sudoers to access
-access $ADMIN_DIR, "chgrp sudo $ADMIN_DIR".
-
-EOF
-                break
-                ;;
-            no | n | No | NO )
-                echo "Exiting."
-                exit 1
-                ;;
-            * )
-                echo -n "Please answer yes or no. "
-                ;;
-        esac
-    done
-fi
+check_permissions
+for d in $(get_uniq_devs); do
+    create_mount_points $(get_label $d)
+done
