Add new functions: trim() is_btrfs() is_lxc() get_lxc_rootfs() lxc_start_stop() Begin work on moving "# Preparing" into prepare() Begin work on moving "# Do backup" into do_backup() Begin work on moving "# Cleanup" into cleanup() Add targetted TODO comments

diff --git a/btrfs-borg b/btrfs-borg
--- a/btrfs-borg
+++ b/btrfs-borg
@@ -158,7 +158,7 @@ if [ -z ${notfound+x} ]; then
 fi
 
 # Other sanity checks
-# TODO: needs to iterate for new $BACKUP_SRCS
+# TODO: needs to iterate for new $backup_srcs
 # Other sanity checks.
 # CLEANUP -> move these to immediately before snapshot is taken
 # eg: pre_snapshot()
@@ -199,7 +199,8 @@ else
 fi
 
 # PREP-STUFF.  TARGET FOR CLEANUP!
-# TODO ITERABLE!
+# TODO: Make it a function
+# LOCAL VARS
 remuser=`echo $repo | cut -d@ -f1`
 remhost=`echo $repo | cut -d@ -f2 | cut -d: -f1`
 remrepo=`echo $repo | cut -d: -f2`
@@ -222,63 +223,110 @@ fi
 echo "Configuration found for $repo"
 # end pre_snapshot()
 
-# Prepare
-echo "Preparing..."
-sync
-btrfs sub sync $ROOT
-sync
-for i in $subs; do
-    btrfs sub snap -r $ROOT/$i $ROOT/$snaps/$i
-    sync
-    btrfs sub sync $ROOT/$snaps/$i
-    sync
-done
-lsubs=`echo $subs | tr ' ' '_'`
-if [ -n "$containers" ]; then
-    unset lxcsnaps
-    for i in $containers; do
-        lxc-stop -n $i
-        lxc-snapshot -n $i
-        sync
-        btrfs sub sync $lxcdir
-        sync
-        lxc-start -n $i
-        if [ -z "$lxcsnaps" ]; then
-            lxcsnaps="`btrfs sub list $lxcdir | grep $i | tail -n1 | awk '{print $NF}'`"
-        else
-            lxcsnaps="$lxcsnaps `btrfs sub list $lxcdir | grep $i | tail -n1 | awk '{print $NF}'`"
-        fi
-    done
-    lcontains="_"
-    lcontains="$lcontains`echo $containers | tr ' ' '_'`"
-fi
-if [ -n "$others" ]; then
-    dirs=""
-    for i in $others; do
-        dirs="$dirs `basename $i`"
-    done
-    loths="_"
-    loths="$loths`echo $dirs | tr ' ' '_'`"
-fi
+trim() {
+    local string="$*"
+    string="${string#"${string%%[![:space:]]*}"}"
+    string="${string%"${string##*[![:space:]]}"}"
+    echo -n "$string"
+}
 
+is_btrfs() {
+    if [ `stat -f --format=%T $1` == 'btrfs' ] && \
+       [ `stat --format=%i $1` -eq 256 ]; then
+        echo "$1 is a btrfs subvolume"
+    else
+        echo "$1 is not a btrfs subvolume"
+        false
+    fi
+}
 
-# Do backup
-echo "Doing backup"
-cd $ROOT/$snaps
-if [ -n "$remuser" ] && [ -n "$remhost" ] && [ -n "$remrepo" ]; then
-    stats=$HOME/time_stats_$DATE
-else
-    stats=$repo/time_stats_$DATE
-fi
+is_lxc() {
+    echo "check for existence of $1/config?"
+    echo "avoid using grep!"
+    echo "grep $1/config for REGEX lxc.rootfs.backend.*btrfs"
+}
+get_lxc_rootfs() {
+    # from main(), use this function to test and get an LXC backup object
+    #at this point $1=$ROOT from $f1 in main() eg: /btrfs-admin/SanDisk
+    #at this point $2="/var/lib/lxc/my-container" from $f2 in main()
+    is_btrfs $1/$2/rootfs
+    ### Test for failure, echo MISCONFIGURED BTRFS-BORG and cleanup
+    if [ $? -eq 0 ]; then
+        #return the full path of subvol to snapshot
+        echo -n "$1/$2/rootfs"
+    else
+        false
+    fi
+}
+
+# TODO: RENAME AND REWORK THIS FUNCTION
+# LOCAL VARS
+lxc_start_stop() {
+    if [ -n "$containers" ]; then
+        unset lxcsnaps
+        for i in $containers; do
+            lxc-stop -n $i
+            lxc-snapshot -n $i
+            sync
+            btrfs sub sync $lxcdir
+            sync
+            lxc-start -n $i
+            if [ -z "$lxcsnaps" ]; then
+                lxcsnaps="`btrfs sub list $lxcdir | grep $i | tail -n1 | awk '{print $NF}'`"
+            else
+                lxcsnaps="$lxcsnaps `btrfs sub list $lxcdir | grep $i | tail -n1 | awk '{print $NF}'`"
+            fi
+        done
+        lcontains="_"
+        lcontains="$lcontains`echo $containers | tr ' ' '_'`"
+    fi
+}
+
+# TODO: Each function needs a comment that documents what arguments
+# it expects and what output it produces.
+# LOCAL VARS
+prepare () {
+    echo "Preparing..."
+    sync
+    btrfs sub sync $ROOT
+    sync
+    for i in $subs; do
+        btrfs sub snap -r $ROOT/$i $ROOT/$snaps/$i
+        sync
+        btrfs sub sync $ROOT/$snaps/$i
+        sync
+    done
+    lsubs=`echo $subs | tr ' ' '_'`
+    if [ -n "$others" ]; then
+        dirs=""
+        for i in $others; do
+            dirs="$dirs `basename $i`"
+        done
+        loths="_"
+        loths="$loths`echo $dirs | tr ' ' '_'`"
+    fi
+}
+
+# TODO: rename this function?  LOCAL VARS
+do_backup() {
+    echo "Doing backup (TODO: Needs to take vars from \$backup_unit"
+    cd $ROOT/$snaps
+    if [ -n "$remuser" ] && [ -n "$remhost" ] && [ -n "$remrepo" ]; then
+        stats=$HOME/time_stats_$DATE
+    else
+        stats=$repo/time_stats_$DATE
+    fi
 borg create $verbos -p --stats $extraargs -C $comp \
      --exclude-caches \
      $repo::$lsubs$lcontains$loths-on-epoch+$DATE\.$comp \
      $subs $lxcsnaps $others
+}
 
 # Cleanup
-# TODO: We now clean up snapshots by default...
-#       Make this configurable in the future
+# Must always clean up snapshots by default.
+#
 # TODO ASAP!!: remove LXC snapshot generated by $btrfs_borg
+#   |-> refer lxc_start_stop()
 # something like:
 #
 #for i in $containers; do
@@ -287,18 +335,22 @@ borg create $verbos -p --stats $extraargs -C $comp \
 #      echo "Removing $EXPIRE"
 #      lxc-snapshot -n get-transmissions -d $EXPIRE
 #done
-echo "Cleaning up Snapshots"
-(time (
-        cd $ROOT/$snaps
-        btrfs sub delete -c $subs
-        echo "Syncing...please be patient, this could be slow"
-        sync
-        btrfs sub sync $ROOT
-        sync)
- 2>&3) 3>&2 2> $stats
-echo -n "Cleanup took "
-cat $stats
-echo
+cleanup() {
+    # TODO LOCAL VARS
+    echo "Cleaning up Snapshots"
+    (time (
+            cd $ROOT/$snaps
+            btrfs sub delete -c $subs
+            echo "Syncing...please be patient, this could be slow"
+            sync
+            btrfs sub sync $ROOT
+            sync)
+     2>&3) 3>&2 2> $stats
+    echo -n "Cleanup took "
+    cat $stats
+    echo
+}
+
 
 unset prune
 if [ -n "$hourly" ]; then prune="-H $hourly"; fi
