Add more checks; minor cleanups.

diff --git a/btrfs-borg b/btrfs-borg
--- a/btrfs-borg
+++ b/btrfs-borg
@@ -15,6 +15,8 @@
 #
 # Copyright (C) 2016  Nicholas D Steeves <nsteeves@gmail.com>
 # 
+# Requires: "install" (usually from coreutils), btrfs-progs, borg
+# Optional: lxc (for now...plan to remove it later), ssh
 
 ROOT='/btrfs-admin' # Mountpoint for the whole volume
                     # Btrfs-borg is designed to operate on named subvolumes.
@@ -116,6 +118,7 @@ COMMAND="`basename $0`"
 export DATE=`date +%s`
 
 # Sanity checks
+# Beginning with requirements
 if [ "`id -u`" -ne 0 ]; then
     cat <<EOF
 Warning, normal user Detected!
@@ -125,7 +128,19 @@ Allowing normal users to create subvolumes is a denial of service
 attack vector, because if more than about 300 subvolumes are created
 btrfs can crash, or halt with ENOSPC error; additionaly, performance
 will suffer with more than ~300 subvolumes.
+
+Additionally, root seems to be required to remove subvolumes!
 EOF
+    NOTFOUND=1
+fi
+for c in install btrfs borg; do
+    type $c >/dev/null 2>&1
+    if [ $? -ne 0 ]; then
+       echo "$c not found"
+       NOTFOUND=1
+    fi
+done
+if [ -z ${NOTFOUND+x} ]; then
     echo -n "Proceed? "
     read choice
     case "$choice" in
@@ -140,8 +155,10 @@ EOF
         * )
             printf "Please answer yes or no\n\n"
             ;;
-            esac
+    esac
 fi
+
+# Other sanity checks
 if [ -d $ROOT/$SNAPS ]; then
     cd $ROOT/$SNAPS
     for i in $SUBS; do
@@ -172,7 +189,7 @@ fi
 if [ $? -ne 0 ]; then
     cat <<EOF
 $REPO/config not found!
-Is your target disk plugged in and mounted?
+Is your backup target disk plugged in and mounted?
 Did you initialize the borg repository?
 EOF
     exit 1
