Version 0.3
* fix accidental upload of wrong filename
* See previous commit for changelog

diff --git a/btrfs-borg b/btrfs-borg
--- a/btrfs-borg
+++ b/btrfs-borg
@@ -1,30 +1,52 @@
 #!/bin/bash
 #
-# btrfs-borg makes snapshots and backs up a list of btrfs snapshotted subvolumes
-# using Borg.  It supports a list of other (probably) non-btrfs directory
-# sources, and 1 second granularity of backups.
+# btrfs-borg makes and backs up a list of btrfs snapshotted subvolumes using
+# Borg.  It supports a list of other (probably) non-btrfs directory sources,
+# and 1 second granularity of backups.
 #
 # Copyright (C) 2016  Nicholas D Steeves <nsteeves@gmail.com>
 # Distributed under the terms of the GPLv2 license.
 # 
 
-ROOT='/btrfs-admin' # for btrfs on /, set this to /
-SNAPS='/btrfs-admin/snapshots'
-SUBS='home var'     # if everything is in one subvolume, set this to /
+ROOT='/btrfs-admin' # Mountpoint for the whole volume
+                    # I mount subvols individually, so this is how I centralise
+                    # administration of my btrfs volume.
+
+SNAPS='snapshots'   # $SNAPS is relative to $ROOT.  eg: /btrfs-admin/snapshots
+                    # On my system it is a normal directory used to centralise
+                    # snapshots.
+
+SUBS='@home rootfs' # $USB is also relative to $ROOT.
+                    # For SUBS, use @home and @for Ubuntu
+                    # and use home and root for Fedora.
+                    # In any case, back up user data before system data.
+
 REPO='/media/usb/Cuboid_Borg'
+#REPO='root@192.168.0.234:'/media/usb/Cuboid_Borg'
 COMP='lz4'          # see borg(1) section on -C COMPRESSION
-OTHERS='/etc'       # I don't use btrfs on /; good backups need both /var & /etc
+# If you don't use btrfs on /; useful backups need both /var & /etc
+# Please note that databases in /var won't be consistent unless you freeze
+# or snapshot them somehow
+OTHERS=''           # eg: /etc, /usr/local  
 
-HOURLY=25
-DAILY=8
-WEEKLY=5
-MONTHLY=13
-YEARLY=4
+                    # Comment out any of the following time periods to disable
+#HOURLY=24          # Disable hourly, because I backup once or twice a week
+DAILY=10
+WEEKLY=4
+MONTHLY=12
+YEARLY=7
 
-# On my system, this is a subvolume that won't be backed up;
-# however, I'd like to keep a list of its contents
-# echo "Building manifests"
-# cd /usr/src && find > /home/backups/src.manifest
+# On my system, these are subvolumes that won't be backed up;
+# however, I'd like to keep a list of their contents
+echo "Building manifests"
+#cd /usr/src && find > /home/backups/src.manifest
+cd /home/triage && find > /home/backups/triage.manifest
+#cd /usr/src && find | ssh sten@192.168.0.234 'cat - > /media/src.manifest'
+#cd /home/triage && find | ssh sten@192.168.0.234 'cat - > /media/triage.manifest'
+
+################################################
+######## Configurable portion ends here ########
+################################################
 
 # Seconds since epoch will allow you to make backups just about
 # as often as possible, unless you theoretically have a *really*
@@ -36,11 +58,11 @@ if [ "`id -u`" -ne 0 ]; then
     echo "$0 must be run as root.  Exiting."
     exit 1
 fi
-if [ -d $SNAPS ]; then
-    cd $SNAPS
+if [ -d $ROOT/$SNAPS ]; then
+    cd $ROOT/$SNAPS
     for i in $SUBS; do
         if [ -d $i ]; then
-            echo "Moving existing $i out of the way to $i-old-$DATE"
+            echo "Moving existing snapshot of $i out of the way to $i-old-$DATE"
             mv $i $i-old-$DATE
         fi
         sync
@@ -48,8 +70,17 @@ if [ -d $SNAPS ]; then
         sync
     done
 else
-    echo "$SNAPS not found! $0 cannot continue."
+    echo "$ROOT/$SNAPS not found! $0 cannot continue."
+    echo "Please mkdir $ROOT/$SNAPS and try again"
+    exit 1
 fi
+
+
+####### TODO ########
+# Add support for checking if $REPO/config exists, when $REPO is
+# accessed over ssh
+##################
+
 if [ -e $REPO/config ]; then
     echo "Configuration found for $REPO"
 else
@@ -66,34 +97,43 @@ sync
 btrfs sub sync $ROOT
 sync
 for i in $SUBS; do
-    btrfs sub snap -r $ROOT/$i $SNAPS/$i
+    btrfs sub snap -r $ROOT/$i $ROOT/$SNAPS/$i
     sync
-    btrfs sub sync $SNAPS/$i
+    btrfs sub sync $ROOT/$SNAPS/$i
     sync
 done
-DIRS=""
-for i in $OTHERS; do
-    DIRS="$DIRS `basename $i`"
-done
-LOTHS=`echo $DIRS | tr ' ' '_'`
+
 LSUBS=`echo $SUBS | tr ' ' '_'`
+if [ "$OTHERS" ]; then
+    DIRS=""
+    for i in $OTHERS; do
+        DIRS="$DIRS `basename $i`"
+    done
+    LOTHS="_"
+    LOTHS="$LOTHS`echo $DIRS | tr ' ' '_'`"
+fi
 
 
 # Do backup
 echo "Doing backup"
-cd $SNAPS
-borg create -v -v -v --stats -p -C $COMP $REPO::$LOTHS\_$LSUBS@$DATE\_$COMP $SUBS $OTHERS
+cd $ROOT/$SNAPS
+borg create -v -v -v --stats -p -C $COMP $REPO::$LSUBS$LOTHS-on-epoch+$DATE\.$COMP $SUBS $OTHERS
 
 
 # Cleanup
 echo "Cleaning up Snapshots"
-for i in $SUBS; do
-    cd $SNAPS
-    btrfs sub del $SNAPS/$i
-done
+cd $ROOT/$SNAPS
+btrfs sub delete -c $SUBS
 echo "Syncing...please be patient, this could be slow"
 sync
 btrfs sub sync $ROOT
 sync
 
-borg prune -v -v -v --stats -H $HOURLY -d $DAILY -w $WEEKLY -m $MONTHLY -y $YEARLY $REPO
+PRUNE=""
+if [ "$HOURLY" ]; then PRUNE="-H $HOURLY"; fi
+if [ "$DAILY" ]; then PRUNE="$PRUNE -d $DAILY"; fi
+if [ "$WEEKLY" ]; then PRUNE="$PRUNE -w $WEEKLY"; fi
+if [ "$MONTHLY" ]; then PRUNE="$PRUNE -m $MONTHLY"; fi
+if [ "$YEARLY" ]; then PRUNE="$PRUNE -y $YEARLY"; fi
+echo "Initiating pruning.  Please do not be alarmed if this takes forever"
+borg prune -v -v -v --stats $PRUNE $REPO
