Add initial LXC support.
Other changes:
  * fix typos and formatting
  * enable passing extra arguments to borg (--exclude-caches example)
  * reenable old verbose behaviour ("-p" argument)
  * stuff that will make restoring from backup easier
    - bundle btrfs-borg script used to make backed
    - bundle list of subvolumes for $ROOT

diff --git a/btrfs-borg b/btrfs-borg
--- a/btrfs-borg
+++ b/btrfs-borg
@@ -24,10 +24,19 @@ SNAPS='snapshots'   # $SNAPS is relative to $ROOT.  eg: /btrfs-admin/snapshots
                     # On my system it is a normal directory used to centralise
                     # snapshots.
 
-SUBS='@home rootfs' # $USB is also relative to $ROOT.
-                    # For SUBS, use @home and @for Ubuntu
-                    # and use home and root for Fedora.
-                    # In any case, back up user data before system data.
+SUBS='@home rootfs' # $SUBS are also relative to $ROOT.  Use @home and @ for
+                    # Ubuntu, and use home and rootfs for Fedora.
+                    # Back up user data before system data, just in case.
+
+CONTAINERS='my-LXC-container my-other-LXC-container'
+
+    # If you have LXC containers on btrfs subvolumes beneath $ROOT,
+    # that are managed by LXC's btrfs backend, then list them here in
+    # the same format you would pass to lxc-stop -n $CONTAINER-NAME.
+    # Please insure that they can be safely stopped without data loss,
+    # because at this point in time (2016-11-12) LXC 2.x containers
+    # need to be stopped before they can be snapshotted.
+    # Leave empty to skip LXC container backup.
 
 REPO='/media/usb/Cuboid_Borg'
 #REMUSER='borg'     # TODO: enable ssh+borg remote
@@ -58,6 +67,12 @@ echo "Manifests have not been configured, please edit $0"
 #cd /home/triage && find > /home/backups/triage.manifest
 #cd /usr/src && find | ssh REMUSER@REMHOST 'cat - > /media/src.manifest'
 #cd /home/triage && find | ssh REMUSER@REMHOST 'cat - > /media/triage.manifest'
+
+# Uncomment this to exclude from the backup directories that
+# contain a file named CACHEDIR.TAG; these can be created like this:
+# touch /home/.cache/CACHETDIR.TAG
+
+# EXTRAARGS='--exclude-caches'
 
 ################################################
 ######## Configurable portion ends here ########
@@ -118,8 +133,25 @@ for i in $SUBS; do
     btrfs sub sync $ROOT/$SNAPS/$i
     sync
 done
-
 LSUBS=`echo $SUBS | tr ' ' '_'`
+if [ "$CONTAINERS" ]; then
+    LXCSNAPS=""
+    for i in $CONTAINERS; do
+        lxc-stop -n $i
+        lxc-snapshot -n $i
+        sync
+        btrfs sub sync /var/lib/lxc
+        sync
+        lxc-start -n $i
+        if [ "$LXCSNAPS" == "" ]; then
+            LXCSNAPS="`btrfs sub list $ROOT | grep $i | tail -n1 | awk '{print $NF}'`"
+        else
+            LXCSNAPS="$LXCSNAPS `btrfs sub list $ROOT | grep $i | tail -n1 | awk '{print $NF}'`"
+        fi
+    done
+    LCONTS="_"
+    LCONTS="$LCONTS`echo $CONTAINERS | tr ' ' '_'`"
+fi
 if [ "$OTHERS" ]; then
     DIRS=""
     for i in $OTHERS; do
@@ -133,22 +165,34 @@ fi
 # Do backup
 echo "Doing backup"
 cd $ROOT/$SNAPS
-(time borg create -v -v -v --stats -p -C $COMP \
-	  $REPO::$LSUBS$LOTHS-on-epoch+$DATE\.$COMP \
-	  $SUBS $OTHERS 2>&3) 3>&2 2> $REPO/time_stats_$DATE
+(time borg create -p -v -v -v --stats $EXTRAARGS -C $COMP \
+      --exclude-caches \
+      $REPO::$LSUBS$LCONTS$LOTHS-on-epoch+$DATE\.$COMP \
+      $SUBS $LXCSNAPS $OTHERS 2>&3) 3>&2 2> $REPO/time_stats_$DATE
 echo "Backup took"
 cat $REPO/time_stats_$DATE
 echo
 
 # Cleanup
+# TODO: We now clean up snapshots by default...
+#       Make this configurable in the future
+# TODO ASAP!!: remove LXC snapshot generated by $0
+# something like:
+#
+#for i in $CONTAINERS; do
+#      lxc-snapshot -L -n $i
+#      EXPIRE="`lxc-snapshot -L -n $i | tail -1 | awk '{print $1}'`"
+#      echo "Removing $EXPIRE"
+#      lxc-snapshot -n get-transmissions -d $EXPIRE
+#done
 echo "Cleaning up Snapshots"
 (time (
-		cd $ROOT/$SNAPS
-		btrfs sub delete -c $SUBS
-		echo "Syncing...please be patient, this could be slow"
-		sync
-		btrfs sub sync $ROOT
-		sync)
+        cd $ROOT/$SNAPS
+        btrfs sub delete -c $SUBS
+        echo "Syncing...please be patient, this could be slow"
+        sync
+        btrfs sub sync $ROOT
+        sync)
  2>&3) 3>&2 2> $REPO/time_stats_$DATE
 echo "Cleanup took"
 cat $REPO/time_stats_$DATE
@@ -162,8 +206,19 @@ if [ "$MONTHLY" ]; then PRUNE="$PRUNE -m $MONTHLY"; fi
 if [ "$YEARLY" ]; then PRUNE="$PRUNE -y $YEARLY"; fi
 echo "Initiating pruning.  Please do not be alarmed if this takes forever"
 (time borg prune -v -v -v --stats $PRUNE $REPO 2>&3) \
-	3>&2 2> $REPO/time_stats_$DATE
+    3>&2 2> $REPO/time_stats_$DATE
 echo "Pruning took"
 cat $REPO/time_stats_$DATE
 echo
 rm $REPO/time_stats_$DATE
+
+# Bundle stuff that will make restoring from backup easier
+if [ -e $REPO/btrfs-borg/$0 ]; then
+    mv $REPO/btrfs-borg/$0 $REPO/btrfs-borg/$0.old
+fi
+install -d -m 500 $0 $REPO/btrfs-borg/$0
+# \/ TODO \/
+#install -d -m 400 $BTRFS-BORG.CSV $REPO/btrfs-borg/$BTRFS-BORG.CSV
+chown 700 $REPO/btrfs-borg
+# TODO: make this iterate for multiple ROOTS
+btrfs sub-list $ROOT > $REPO/btrfs-borg/subvolumes_of_$ROOT
