Begin documenting functions, and... Indentation changes related to enabling tab-less auto-indent-on-save in my editor

diff --git a/btrfs-borg-functions b/btrfs-borg-functions
--- a/btrfs-borg-functions
+++ b/btrfs-borg-functions
@@ -12,6 +12,9 @@
 #
 # Copyright (C) 2016-2017  Nicholas D Steeves <nsteeves@gmail.com>
 
+# function: trim leading and trailing whitespace from strings
+# parameter: string, taken from a field of a CSV
+# TODO: test to see if this is truly necessary, and if not, drop it
 trim() {
     local string="$*"
     string="${string#"${string%%[![:space:]]*}"}"
@@ -19,89 +22,90 @@ trim() {
     echo -n "$string"
 }
 
-# Other sanity checks
+# function: Other sanity checks
+# parameter: To be written
 # TODO: needs to iterate for new $backup_srcs
-# Other sanity checks.
-# CLEANUP -> move these to immediately before snapshot is taken
+#       Other sanity checks.
+#       CLEANUP -> move these to immediately before snapshot is taken
 pre_snapshot() {
-if [ -d "$ROOT/$snaps" ]; then
-    cd "$ROOT/$snaps"
-    for i in $subs; do
-        if [ -d "$i" ]; then
-            AGE=$(stat -c %Y "$i")
-# this \/ isn't very nice...make snapshots as btrfs-borg-$i or $i.borg-snap instead
-            echo "Moving existing snapshot of $i out of the way to
+    if [ -d "$ROOT/$snaps" ]; then
+        cd "$ROOT/$snaps"
+        for i in $subs; do
+            if [ -d "$i" ]; then
+                AGE=$(stat -c %Y "$i")
+                # this \/ isn't very nice...make snapshots as btrfs-borg-$i or $i.borg-snap instead
+                echo "Moving existing snapshot of $i out of the way to
 $i@$AGE"
-            echo "TODO make snapshots as btrfs-borg_$i or $i.borg-snap instead"
-            mv "$i" "$i"@"$AGE"
-        fi
-        sync
-        btrfs sub sync "$ROOT"
-        sync
-    done
-else
-    echo "$SNAPS not found! $COMMAND cannot continue."
-    echo "create $SNAPS?"
-    if [ -z ${NOTFOUND+x} ]; then
-        echo -n "Proceed? "
-        while true; do
-              read choice
-              case "$choice" in
-                  yes | y | Yes | YES )
-                      echo "Creating $SNAPS"
-                      install -d -m 700
-                      break
-                      ;;
-                  no | n | No | NO )
-                      echo "Exiting safely."
-                      exit 1
-                      ;;
-                  * )
-                      printf "Please answer yes or no\n\n"
-                      ;;
-              esac
+                echo "TODO make snapshots as btrfs-borg_$i or $i.borg-snap instead"
+                mv "$i" "$i"@"$AGE"
+            fi
+            sync
+            btrfs sub sync "$ROOT"
+            sync
         done
+    else
+        echo "$SNAPS not found! $COMMAND cannot continue."
+        echo "create $SNAPS?"
+        if [ -z ${NOTFOUND+x} ]; then
+            echo -n "Proceed? "
+            while true; do
+                read choice
+                case "$choice" in
+                    yes | y | Yes | YES )
+                        echo "Creating $SNAPS"
+                        install -d -m 700
+                        break
+                        ;;
+                    no | n | No | NO )
+                        echo "Exiting safely."
+                        exit 1
+                        ;;
+                    * )
+                        printf "Please answer yes or no\n\n"
+                        ;;
+                esac
+            done
+        fi
+        exit 1
     fi
-    exit 1
-fi
 
-# PREP-STUFF.  TARGET FOR CLEANUP!
-# TODO: Make it a function
-# LOCAL VARS
-remuser="$(echo $repo | cut -d@ -f1)"
-remhost="$(echo $repo | cut -d@ -f2 | cut -d: -f1)"
-remrepo="$(echo $repo | cut -d: -f2)"
+    # PREP-STUFF.  TARGET FOR CLEANUP!
+    # TODO: Make it a function
+    # LOCAL VARS
+    remuser="$(echo $repo | cut -d@ -f1)"
+    remhost="$(echo $repo | cut -d@ -f2 | cut -d: -f1)"
+    remrepo="$(echo $repo | cut -d: -f2)"
 
-# TODO: non-iterable sanity checks TARGET FOR CLEANUP!
-# Check for existence of intended borg REPO
-if [ -n "$remuser" ] && [ -n "$remhost" ] && [ -n "$remrepo" ]; then
-    ssh $remuser@$remhost "test -e $remrepo/config"
-elif [ ! -f "$repo/config" ]; then
-    false
-fi
-if [ $? -ne 0 ]; then
-    cat <<EOF
+    # TODO: non-iterable sanity checks TARGET FOR CLEANUP!
+    # Check for existence of intended borg REPO
+    if [ -n "$remuser" ] && [ -n "$remhost" ] && [ -n "$remrepo" ]; then
+        ssh $remuser@$remhost "test -e $remrepo/config"
+    elif [ ! -f "$repo/config" ]; then
+        false
+    fi
+    if [ $? -ne 0 ]; then
+        cat <<EOF
 $repo/config not found!
 Is your backup target disk plugged in and mounted?
 Did you initialise the borg repository?
 EOF
-    exit 1
-fi
-echo "Configuration found for $repo"
+        exit 1
+    fi
+    echo "Configuration found for $repo"
 }
 # end pre_snapshot()
 
 is_btrfs() {
     if [ "$(stat -f --format=%T $1)" == 'btrfs' ]; then
-	echo "$1 is a btrfs volume"
+        echo "$1 is a btrfs volume"
     else
-	echo "$1 is not a btrfs volume"
+        echo "$1 is not a btrfs volume"
     fi
 }
 
 is_subvolume() {
     if [ "$(stat -f --format=%T $1)" == 'btrfs' ] && \
-       [ "$(stat --format=%i $1)" -eq 256 ]; then
+           [ "$(stat --format=%i $1)" -eq 256 ]; then
         echo "$1 is a btrfs subvolume"
     else
         echo "$1 is not a btrfs subvolume"
@@ -109,12 +113,18 @@ is_subvolume() {
     fi
 }
 
+# function: returns true if an LX container is found
+# parameter: filesystem path
+# TODO: write it
 is_lxc() {
     echo "check for existence of $1/config?"
     echo "avoid using grep!"
     echo "grep $1/config for REGEX lxc.rootfs.backend.*btrfs"
 }
 
+# function:
+# parameter: path that passes is_lxc's test
+# TODO: make this function actually work
 get_lxc_rootfs() {
     # from main(), use this function to test and get an LXC backup object
     #at this point $1=$ROOT from $f1 in main() eg: /btrfs-admin/SanDisk
@@ -188,10 +198,10 @@ do_backup() {
     else
         stats=$repo/time_stats_$DATE
     fi
-borg create $verbos -p --stats $extraargs -C $comp \
-     --exclude-caches \
-     $repo::$lsubs$lcontains$loths-on-epoch+$DATE\.$comp \
-     $subs $lxcsnaps $others
+    borg create $verbos -p --stats $extraargs -C $comp \
+         --exclude-caches \
+         $repo::$lsubs$lcontains$loths-on-epoch+$DATE\.$comp \
+         $subs $lxcsnaps $others
 }
 
 # Cleanup
@@ -299,21 +309,21 @@ bundle_stuff() {
 }
 
 verify() {
-   echo "do verification"
-   echo success || fail from $? according to VERBOS setting
-   # get verbos setting from `which btrfs-borg?`
-   # get the list of archives to verify from somewhere
-   # it would also be good to have a more verbose way to
-   # verify the whole repo
+    echo "do verification"
+    echo success || fail from $? according to VERBOS setting
+    # get verbos setting from `which btrfs-borg?`
+    # get the list of archives to verify from somewhere
+    # it would also be good to have a more verbose way to
+    # verify the whole repo
 
-   # That said, I'm thinking about using the epoch+seconds
-   # thing to allow verification of all archives since 34198723649
-   # eg: verify_since=`date -d "-3 month" +%s`
-   # parse the date stamp, and if >= $verify_since then borg extract
-   # --dry-run it
+    # That said, I'm thinking about using the epoch+seconds
+    # thing to allow verification of all archives since 34198723649
+    # eg: verify_since=`date -d "-3 month" +%s`
+    # parse the date stamp, and if >= $verify_since then borg extract
+    # --dry-run it
 
-   # Alternatively, get the date stamp of the most recent archive, and verify
-   # all archives taken from that (value minus 24h) range.
+    # Alternatively, get the date stamp of the most recent archive, and verify
+    # all archives taken from that (value minus 24h) range.
 
-   # When borg supports it, switch to using --verify-data
+    # When borg supports it, switch to using --verify-data
 }
