New function: repo_exists()
Relocate and restructure old prototype

diff --git a/btrfs-borg-functions b/btrfs-borg-functions
--- a/btrfs-borg-functions
+++ b/btrfs-borg-functions
@@ -171,12 +171,58 @@ create_mount_points() {
     done
 }
 
+# function: tests arg to see if it is a bizarrely named local path or
+#           or if it is ssh connected
+# parameter: string, /path/to/borg/repo, or
+#            user@host:/path/to/borg/repo
+# returns: exit code
+repo_exists() {
+    # let's suppose $1=bizarre@dir_name:has:colons/oh/no
+    if [ -e "$1" ]; then
+        echo "Please consider naming $1 without @s and :s"
+        echo "It looks like bizarre@dir_name:has:colons/oh/no"
+        # Check for existence of borg repo
+        if [ ! -f "$1/config" ]; then
+            cat <<EOF
+$1/config not found!
+Is your backup target disk plugged in and mounted?
+Did you initialise the borg repository?
+EOF
+            exit 102
+            # no such file or directory
+        fi
+    else
+        local remuser; local remhost; local remrepo
+        remuser="$(echo -n $1 | cut -d@ -f1)"
+        remhost="$(echo -n $1 | cut -d@ -f2 | cut -d: -f1)"
+        remrepo="$(echo -n $1 | cut -d: -f2)"
+        # Check for existence of borg repo
+        if [ -n "$remuser" ] && [ -n "$remhost" ] && [ -n "$remrepo" ]; then
+            ssh $remuser@$remhost "test -e $remrepo/config"
+            if [ $? -ne 0 ]; then
+                cat <<EOF
+$1/config not found!
+Is your backup target disk plugged in and mounted?
+Did you initialise the borg repository?
+EOF
+            fi
+            echo "Configuration found for $repo"
+            return 14
+            # bad address
+        fi
+    fi
+}
+
 # function: Other sanity checks
 # parameter: To be written
 # TODO: needs to iterate for new $backup_srcs
 #       Other sanity checks.
 #       CLEANUP -> move these to immediately before snapshot is taken
-# TODO: needs magic!  Possibly needs rewrite...  eg: right now it needs both $ADMIN_DIR/$label_or_dev/$SNAPS_DIR AND the backup src-object...but I haven't written the automatically find src-object (eg: subvolume) yet.  The loop should probably be external to the function.
+# TODO: needs magic!  Possibly needs rewrite...  eg: right now it
+#       needs both $ADMIN_DIR/$label_or_dev/$SNAPS_DIR AND the backup
+#       src-object...but I haven't written the automatically find
+#       src-object (eg: subvolume) yet.  The loop should probably be
+#       external to the function.
 pre_snapshot() {
     cd "$ROOT/$SNAPS_DIR"
     for i in $subs; do
@@ -193,30 +239,6 @@ $i@$AGE"
         btrfs subvolume sync "$ROOT"
         sync
     done
-
-    # PREP-STUFF.  TARGET FOR CLEANUP!
-    # TODO: Make it a function
-    # LOCAL VARS
-    remuser="$(echo $repo | cut -d@ -f1)"
-    remhost="$(echo $repo | cut -d@ -f2 | cut -d: -f1)"
-    remrepo="$(echo $repo | cut -d: -f2)"
-
-    # TODO: non-iterable sanity checks TARGET FOR CLEANUP!
-    # Check for existence of intended borg REPO
-    if [ -n "$remuser" ] && [ -n "$remhost" ] && [ -n "$remrepo" ]; then
-        ssh $remuser@$remhost "test -e $remrepo/config"
-    elif [ ! -f "$repo/config" ]; then
-        false
-    fi
-    if [ $? -ne 0 ]; then
-        cat <<EOF
-$repo/config not found!
-Is your backup target disk plugged in and mounted?
-Did you initialise the borg repository?
-EOF
-        exit 1
-    fi
-    echo "Configuration found for $repo"
 }
 # end pre_snapshot()
 
